-- Canonical contract is 768 dimensions, explicitly requested from Gemini.
-- The former 3072-d migration conflicted with the proxy and HNSW limits.
-- For existing deployments, migration 004 handles incompatible derived vectors.
